### PR TITLE
add support for multiple OctopusDeploy servers

### PR DESCRIPTION
**Pull request by phoewass**
# Description
This PR add support for multiple OctopusDeploy servers

See [JENKINS-41269](https://issues.jenkins-ci.org/browse/JENKINS-41269).
Closes #12

Details:
- Added ServerId varaible to OctopusServer details
- Added OctopusDeployServer: a model class that encapsulates Octopus server details.
- Added AbstractOctopusDeployRecorder: used to provide utilities to share data with DescriptorImpl and remove redundant code from OctopusDeployReleaseRecorder and OctopusDeployDeploymentRecorder
- Changed Job configuration UI to include an input to select ServerId
- Changed Plugin configuration UI to enable adding multiple Octopus Deploy servers
- Changed Gracefully handle old (version 1.6 or less) plugin configuration format
- Added defaultServerId to be used in jobs created with older version of OctopusDeploy Plugin  and enable these jobs to be kicked off without any modification
- Added show the defaultServerId  in serverId field when creating a new job

### TODO
- [x] Allow the plugin to be backward compatible:
 - Job config: Currently the jobs created using older versions break).
This could be mitigated by providing a "default" Octopus Deploy server
- Plugin config: To be discussed.

### Desired reviewers
@badriance

### CODE REVIEW

**Comment by badriance** [comment]
I hope to get this reviewed by the end of this week.

**Comment by badriance** [comment]
After reviewing and thinking more on this, I'd like to see this changed so we can maintain upgrade compatibility. Change the existing single host/api key to be the default, then add optional additions in global config.

then on each recorder, add advanced option for host/api pair override.

@phoewass thoughts?

**Comment by phoewass** [comment]
I agree, I think it's feasible.
The only gotcha is how it is going to be implemented from the Job config side.

**Comment by phoewass** [comment]
@badriance Did you had time to review this ?

**Pull request merged**
